# Generated by Django 5.0.12 on 2025-02-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='INV_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=255)),
                ('Location_DC', models.CharField(max_length=255)),
                ('Store_code', models.CharField(max_length=50)),
                ('Store_name', models.CharField(max_length=255)),
                ('Store_State', models.CharField(max_length=255)),
                ('Store_Zone', models.CharField(max_length=255)),
                ('Inv_date', models.DateField()),
                ('Invoice_number', models.CharField(max_length=50)),
                ('Total_Inv_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Document_type', models.CharField(max_length=50)),
                ('Created_from', models.CharField(max_length=50)),
                ('Shiping_addr', models.TextField()),
                ('Billing_addr', models.TextField()),
                ('IRN_Details', models.TextField(blank=True, null=True)),
                ('ERP_Type', models.CharField(max_length=50)),
                ('Item_code', models.CharField(max_length=50)),
                ('Item_Desc', models.CharField(max_length=255)),
                ('Invoice_quantity', models.PositiveIntegerField()),
                ('Item_Category', models.CharField(max_length=50)),
                ('Item_Rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Tax_code', models.CharField(max_length=50)),
            ],
        ),
    ]
